VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITransformer"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("Lambda.Interface")
'@FunctionInterface
'@Interface

'@ModuleDescription: Functional Interface is an interface with having only one method
'                                  More details is here : https://www.geeksforgeeks.org/functional-interfaces-java/
Option Explicit

Public Function Apply(GivenText As String) As String
    
End Function
